[tool.poetry]
name = "live-novidades"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyright = "^1.1.329"
mypy = "^1.5.1"

[tool.pyright]
python_version = '3.12'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
