[tool.poetry]
name = "live-rich"
version = "0.1.0"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]
readme = "README.md"
packages = [{include = "live_rich"}]

[tool.poetry.dependencies]
python = "^3.11"
rich = "^12.6.0"
rich-cli = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
