[tool.poetry]
name = "live_moviepy"
version = "0.1.0"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
moviepy = "^1.0.3"
pygame = "^2.1.2"
pydub = "^0.25.1"
vosk = "^0.3.43"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
